In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
data=pd.read_csv('income(1).csv',na_values=[" ?"])

In [3]:
data.isnull().sum()

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [4]:
missing=data[data.isnull().any(axis=1)]

In [5]:
data2=data.dropna(axis=0)

In [6]:
data2


age       JobType         EdType        maritalstatus  \
0       45       Private        HS-grad             Divorced   
1       24   Federal-gov        HS-grad        Never-married   
2       44       Private   Some-college   Married-civ-spouse   
3       27       Private            9th        Never-married   
4       20       Private   Some-college        Never-married   
...    ...           ...            ...                  ...   
31973   34     Local-gov        HS-grad        Never-married   
31974   34     Local-gov   Some-college        Never-married   
31975   23       Private   Some-college   Married-civ-spouse   
31976   42     Local-gov   Some-college   Married-civ-spouse   
31977   29       Private      Bachelors        Never-married   

             occupation     relationship    race   gender  capitalgain  \
0          Adm-clerical    Not-in-family   White   Female            0   
1          Armed-Forces        Own-child   White     Male            0   
2        Prof-specialty          Husband   White     Male            0   
3          Craft-repair   Other-relative   White     Male            0   
4                 Sales    Not-in-family   White     Male            0   
...                 ...              ...     ...      ...          ...   
31973   Farming-fishing    Not-in-family   Black     Male          594   
31974   Protective-serv    Not-in-family   White   Female            0   
31975      Adm-clerical          Husband   White     Male            0   
31976      Adm-clerical             Wife   White   Female            0   
31977    Prof-specialty    Not-in-family   White     Male            0   

       capitalloss  hoursperweek   nativecountry  \
0                0            28   United-States   
1                0            40   United-States   
2                0            40   United-States   
3                0            40          Mexico   
4                0            35   United-States   
...            ...           ...             ...   
31973            0            60   United-States   
31974            0            40   United-States   
31975            0            40   United-States   
31976            0            40   United-States   
31977            0            40   United-States   

                             SalStat  
0       less than or equal to 50,000  
1       less than or equal to 50,000  
2                greater than 50,000  
3       less than or equal to 50,000  
4       less than or equal to 50,000  
...                              ...  
31973   less than or equal to 50,000  
31974   less than or equal to 50,000  
31975   less than or equal to 50,000  
31976   less than or equal to 50,000  
31977   less than or equal to 50,000  

[30162 rows x 13 columns]

In [7]:
data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data2['SalStat'])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64


C:\Users\SHREYA~1\AppData\Local\Temp/ipykernel_13596/784685041.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})


In [10]:
new_data=pd.get_dummies(data2, drop_first=True)

In [11]:
columns_list = list(new_data.columns)
print(columns_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Local-gov', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-s

In [12]:
features = list(set(columns_list)-set(['SalStat']))
print(features)

['EdType_ Prof-school', 'nativecountry_ El-Salvador', 'nativecountry_ Vietnam', 'relationship_ Not-in-family', 'occupation_ Protective-serv', 'occupation_ Craft-repair', 'nativecountry_ Cuba', 'relationship_ Wife', 'occupation_ Transport-moving', 'occupation_ Sales', 'race_ Asian-Pac-Islander', 'nativecountry_ Guatemala', 'nativecountry_ Iran', 'maritalstatus_ Widowed', 'EdType_ 9th', 'nativecountry_ Yugoslavia', 'race_ Black', 'race_ Other', 'JobType_ State-gov', 'nativecountry_ France', 'EdType_ Doctorate', 'EdType_ Masters', 'occupation_ Tech-support', 'EdType_ 7th-8th', 'nativecountry_ Hong', 'nativecountry_ Italy', 'occupation_ Priv-house-serv', 'nativecountry_ Peru', 'EdType_ Some-college', 'JobType_ Self-emp-not-inc', 'relationship_ Own-child', 'nativecountry_ Dominican-Republic', 'hoursperweek', 'nativecountry_ Laos', 'nativecountry_ Mexico', 'nativecountry_ China', 'nativecountry_ Japan', 'JobType_ Without-pay', 'nativecountry_ Germany', 'occupation_ Armed-Forces', 'nativecoun

In [13]:
y=new_data['SalStat'].values
print(y)

[0 0 1 ... 0 0 0]


In [14]:
x=new_data[features].values
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)

In [17]:
KNN_classifier = KNeighborsClassifier(n_neighbors = 5)

In [18]:
KNN_classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [20]:
prediction = KNN_classifier.predict(x_test)

In [21]:
confusionMmatrix = confusion_matrix(y_test,prediction)

In [22]:
print(confusionMmatrix)

[[6173  650]
 [ 843 1383]]


In [23]:
accuracy_score = accuracy_score(y_test, prediction)
print(accuracy_score)

0.8350093933031274


In [24]:
print('Misclassified samples: %d' % (y_test != prediction).sum())

Misclassified samples: 1493


In [25]:
Misclassified_sample = []
for i in range(1,20):
    knn = KNeighborsClassifier (n_neighbors=i)
    knn.fit(x_train, y_train)
    pred_i = knn.predict(x_test)
    Misclassified_sample.append((y_test != pred_i).sum())
print(Misclassified_sample)

[1766, 1516, 1515, 1436, 1493, 1438, 1451, 1432, 1458, 1436, 1441, 1447, 1451, 1423, 1413, 1390, 1424, 1396, 1434]
